import pandas

df = pandas.read_excel(r'C:\Users\bluek\OneDrive\Desktop\CS 591\data3.xlsx')

deidentIDData = pandas.DataFrame(df,columns=['DeidentID'])
recIDData = pandas.DataFrame(df,columns=['RecID'])
AntibodyTestDtData = pandas.DataFrame(df,columns=['AntibodyTestDt'])
IValueData = pandas.DataFrame(df,columns=['IAAValue'])
IStatusData = pandas.DataFrame(df,columns=['IAAStatus'])
I2ValueData = pandas.DataFrame(df,columns=['IA2Value'])
I2StatusData = pandas.DataFrame(df,columns=['IA2Status'])
GValueData = pandas.DataFrame(df,columns=['GAD65Value'])
GStatusData = pandas.DataFrame(df,columns=['GAD65Status'])
ZValueData = pandas.DataFrame(df,columns=['ZnT8Value'])
ZStatusData = pandas.DataFrame(df,columns=['ZnT8Status'])
HTestData = pandas.DataFrame(df,columns=['Hba1cTestDt'])
HValueData = pandas.DataFrame(df,columns=['Hba1cValue'])

print(deidentIDData)
print(recIDData)
print(AntibodyTestDtData)
print(IValueData)
print(IStatusData)
print(I2ValueData)
print(I2StatusData)
print(GValueData)
print(GStatusData)
print(ZValueData)
print(ZStatusData)
print(HTestData)
print(HValueData)